### ISSUE TITLE
Add "Sticker Wizard"

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#235]
Add wizard for creating & exporting (as `.dat`) custom LDraw "sticker" parts directly in LeoCAD.

- http://www.ldraw.org/article/339
  - https://news.lugnet.com/cad/dev/?q=Stickers+in+LDraw&qn=20
  - http://anoved.net/2010/04/using-ldview-to-make-it-easier-to-add-parts-to-your-ldraw-library/
  - https://bricks.stackexchange.com/questions/6220/how-to-import-an-unofficial-parts-archive-into-ldraw

### TODO

- [ ] add *"Sticker Wizard"* GUI
  - http://www.melkert.net/test/stickerGen.html
  - http://www.scottwardlaw.com/sticker_generator/
    - https://forums.ldraw.org/showthread.php?tid=1674&pid=1684
    - http://www.brickshelf.com/cgi-bin/gallery.cgi?f=267156
    - https://news.lugnet.com/cad/?n=14972
- [ ] add *"Text"* tool in *"Sticker Wizard"* for adding text on sticker
  - https://wiki.ldraw.org/wiki/Txt2dat
  - http://www.br-eng.info/my-lego-roscomenu-29/my-ldraw-roscomenu-45/50-txt2dat
  - http://www.br-eng.info/files/txt2dat/txt2dat-0.2.3-src.tar.gz
- [ ] support bitmap templates (`.png`)
  - https://www.leocad.org/docs/texmap.html
- [ ] support vector templates (`.svg`)
  - https://wiki.ldraw.org/wiki/Stickers:_making_a_random_shape_one
- [ ] export resulted sticker as separate file (`.dat`)
  - Sticker numbering (formed / plain): https://news.lugnet.com/cad/dat/parts/?n=6446
  - http://www.brickshelf.com/cgi-bin/gallery.cgi?f=543082
    - http://www.brickshelf.com/gallery/lg008823/TrainPosterV2/stickertest.ldr

### RELATED

- https://github.com/leozide/leocad/issues/195
- https://github.com/leozide/leocad/issues/45

**Comment by Symbian9** [comment]
Partially by implementing `SvgToDat` into *LeoCAD* would solve this task

- https://github.com/tcobbs/SvgToDat

@tcobbs, any ideas?

**Comment by tcobbs** [comment]
I wrote SvgToDat years ago, and I don't remember how it works, but a quick glance at the source code shows that it uses GLU for tessellation. I know it doesn't fully support SVG syntax, but it could be a good starting place. The tessellation could probably be replaced with any 3rd-party tessellation library. Whether or not it is something that would be useful in LeoCAD isn't something I can really answer.

**Comment by leozide** [comment]
This is beyond the scope of the app, there are other tools designed for parts creation
